### ISSUE TITLE
Unable to fetch multiple rows

### ISSUE THREAD

**Issue by skanga** [bitsummation/pickaxe#3]
select
  pick 'p.row span.txt span.pl a' --title
from download page
  'https://sfbay.craigslist.org/search/mcy?minAsk=1000&maxAsk=8000&query=cruiser'
where nodes = 'div.content div.rows'

Why does this query only return a single record?

**Comment by breeve1** [comment]
So you need to select multiple elements in the where clause. Think array of elements. The select then selects under those. The below query works,

select
pick 'span.txt span.pl a' --title
from download page
'https://sfbay.craigslist.org/search/mcy?minAsk=1000&maxAsk=8000&query=cruiser'
where nodes = 'div.content div.rows p'

**Comment by skanga** [comment]
Thanks. That works.
