### ISSUE TITLE
Same results. What's wrong?

### ISSUE THREAD

**Issue by adam-acosta** [bitsummation/pickaxe#5]
No matter what page I try I get the same type result 1 row. Does this app still function? Need help. Really want to use this. Thanks.

![image](https://user-images.githubusercontent.com/1189675/34912996-79b5416c-f8be-11e7-9ce1-adaf3fbf7748.png)

**Comment by breeve1** [comment]
So you have to specify a where clause and pick statements to specify what you want. This works
```
select
	pick 'td:first-child' as name,
	pick 'td:nth-child(2)' as debut,
	pick 'td:nth-child(3)' as finalGame
from download page 'https://en.wikipedia.org/wiki/List_of_Major_League_Baseball_players_(A)'
where nodes = 'table.wikitable tbody tr'

```

**Comment by breeve1** [comment]
Or better get them all

```
select
	pick 'td:first-child' as name,
	pick 'td:nth-child(2)' as debut,
	pick 'td:nth-child(3)' as finalGame
from download page (
	select
		'https://en.wikipedia.org' + pick 'a' take attribute 'href'
	from download page 'https://en.wikipedia.org/wiki/Lists_of_Major_League_Baseball_players'
	where nodes = 'div.toc li'
)
where nodes = 'table.wikitable tbody tr'

```

**Comment by adam-acosta** [comment]
Thanks. I had tried the first 2 snippets listed and assumed the output was incorrect. Sorry, wanted to see if it worked first before trying to understand how it works. Guess I needed to try the 3rd. Thanks again.
